test5

diff --git a/.github/workflows/android_fastlane_firebase_app_distribution_workflow.yml b/.github/workflows/android_fastlane_firebase_app_distribution_workflow.yml
--- a/.github/workflows/android_fastlane_firebase_app_distribution_workflow.yml
+++ b/.github/workflows/android_fastlane_firebase_app_distribution_workflow.yml
@@ -43,6 +43,13 @@ jobs:
           GDRIVE_ACCESS_TOKEN: ${{ secrets.GDRIVE_ACCESS_TOKEN }}
         working-directory: android
         run: |
-          ./gradlew clean assembleRelease
+          # Find APK path after build
           APK_PATH=$(find app/build/outputs/apk/release -name "*.apk" | head -n 1)
-          gdrive upload --parent <FOLDER_ID> "$APK_PATH"
+          
+          # Ensure APK exists
+          if [ -f "$APK_PATH" ]; then
+            gdrive upload --parent <FOLDER_ID> "$APK_PATH"
+          else
+            echo "APK file not found!"
+            exit 1
+          fi
